"""create many tables

Revision ID: c13d280ba8f9
Revises: 6533c86ff562
Create Date: 2025-05-21 05:30:20.160659

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c13d280ba8f9"
down_revision: Union[str, None] = "6533c86ff562"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
    )
    op.create_table(
        "carts",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_carts_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_carts")),
    )
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=False),
        sa.Column("weight_g", sa.Integer(), nullable=True),
        sa.Column("volume_ml", sa.Integer(), nullable=True),
        sa.Column("stock", sa.Integer(), server_default="0", nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_products_category_id_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("name", name=op.f("uq_products_name")),
    )
    op.create_table(
        "cart_food_associations",
        sa.Column("count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "unit_price", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("cart_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["carts.id"],
            name=op.f("fk_cart_food_associations_cart_id_carts"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_cart_food_associations_product_id_products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_food_associations")),
        sa.UniqueConstraint(
            "cart_id",
            "product_id",
            name=op.f("uq_cart_food_associations_cart_id_product_id"),
        ),
    )
    op.create_table(
        "option_groups",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_option_groups_product_id_products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_option_groups")),
    )
    op.create_table(
        "options",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("price_delta", sa.Integer(), nullable=False),
        sa.Column("option_group_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["option_group_id"],
            ["option_groups.id"],
            name=op.f("fk_options_option_group_id_option_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_options")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("options")
    op.drop_table("option_groups")
    op.drop_table("cart_food_associations")
    op.drop_table("products")
    op.drop_table("carts")
    op.drop_table("categories")
    # ### end Alembic commands ###
